---
- name: create Development lifecycle environment for the Satellite Server
  redhat.satellite.lifecycle_environment:
    server_url: "https://{{ var_workshop_satellite_url }}"
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    organization: "Default Organization"
    name: "Development"
    prior: "Library"

- name: create Test lifecycle environment for the Satellite Server
  redhat.satellite.lifecycle_environment:
    server_url: "https://{{ var_workshop_satellite_url }}"
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    organization: "Default Organization"
    name: "Test"
    prior: "Development"

- name: create Production lifecycle environment for the Satellite Server
  redhat.satellite.lifecycle_environment:
    server_url: "https://{{ var_workshop_satellite_url }}"
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    organization: "Default Organization"
    name: "Production"
    prior: "Test"

- name: "Enable Satellite-Client 6 for RHEL 9 repository with label"
  redhat.satellite.repository_set:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    organization: "Default Organization"
    label: satellite-client-6-for-rhel-9-x86_64-rpms
    all_repositories: true
    state: enabled

- name: "Enable RHEL 9 BaseOS RPMs repository with label"
  redhat.satellite.repository_set:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    organization: "Default Organization"
    label: rhel-9-for-x86_64-baseos-rpms
    repositories:
      - releasever: "9" 
    state: enabled

- name: "Enable RHEL 9 AppStream RPMs repository with label"
  redhat.satellite.repository_set:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    organization: "Default Organization"
    label: rhel-9-for-x86_64-appstream-rpms
    repositories:
      - releasever: "9" 
    state: enabled
    
- name: "Enable Directory Server RPMs repositories with label"
  redhat.satellite.repository_set:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    organization: "Default Organization"
    label: dirsrv-12-for-rhel-9-x86_64-rpms
    repositories:
      - releasever: "9"
    state: enabled

#Sync Repos
- name: "Sync the Directory Server Repo"
  redhat.satellite.repository_sync:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    repository: "Red Hat Directory Server 12 for RHEL 9 x86_64 RPMs 9"
    product: "Red Hat Directory Server"
    organization: "Default Organization"

- name: "Sync the RHEL BaseOS Server Repo"
  redhat.satellite.repository_sync:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    repository: "Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
    organization: "Default Organization"

- name: "Sync the RHEL AppStream Server Repo"
  redhat.satellite.repository_sync:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    repository: "Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9"
    product: "Red Hat Enterprise Linux for x86_64"
    organization: "Default Organization"

- name: "Sync the Satellite client Server Repo"
  redhat.satellite.repository_sync:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    repository: "Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs"
    product: "Red Hat Enterprise Linux for x86_64"
    organization: "Default Organization"

# Check for running sync tasks and pause until sync is complete
- name: Search for running repo/Capsule sync tasks and CV Publish tasks
  redhat.satellite.resource_info:
    server_url: "https://{{ var_workshop_satellite_url }}"
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    resource: foreman_tasks
    search: "(label = Actions::Katello::Repository::Sync or label = Actions::Katello::CapsuleContent::Sync or label = Actions::Katello::ContentView::CapsuleSync or label= Actions::Katello::ContentView::Publish) and state = running"
  register: tasks

- name: Wait for all found tasks to finish
  redhat.satellite.wait_for_task:
    server_url: "https://{{ var_workshop_satellite_url }}"
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    task: "{{ item }}"
    timeout: 900 
  loop: "{{ tasks.resources | map(attribute='id') | list }}"

- name: "Enable the Directory Server Repo and set to Immmediate"
  redhat.satellite.repository:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    name: "Red Hat Directory Server 12 for RHEL 9 x86_64 RPMs 9"
    state: present
    content_type: "yum"
    product: "Red Hat Directory Server"
    organization: "Default Organization"
    url: "https://cdn.redhat.com/content/dist/rhel9/9/x86_64/resilientstorage/os"
    download_policy: immediate

#Ensure Capsule will autosync after CV publish/promote    
- name: Set Capsule to sync on LCE change
  become: true
  shell: 'hammer setting set --name foreman_proxy_content_auto_sync --value True'
    
- name: "Update the Caspule settings"
  redhat.satellite.smart_proxy:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    name: "capsule.{{ var_subdomain }}"
    url: "https://capsule.{{ var_subdomain }}:9090"
    download_policy: "on_demand"
    lifecycle_environments:
      - "Development"
      - "Test"
      - "Production"
    organizations:
      - "Default Organization"
    locations:
      - "Default Location"
    state: present

- name: "Create or update Red Hat content view"
  redhat.satellite.content_view:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    name: "RHEL9-CV"
    organization: "Default Organization"
    repositories:
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
        product: 'Red Hat Enterprise Linux for x86_64'
      - name: 'Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs'
        product: 'Red Hat Enterprise Linux for x86_64'
  
- name: "Publish Red Hat Content View"
  redhat.satellite.content_view_version:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    content_view: "RHEL9-CV"
    organization: "Default Organization"
    version: "1.0"
    lifecycle_environments:
      - Development
      - Test
      - Production

- name: "Create client activation key"
  redhat.satellite.activation_key:
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    name: "client_key"
    organization: "Default Organization"
    lifecycle_environment: "Development"
    content_view: 'RHEL9-CV'
    auto_attach: true
    release_version: 9

- name: Create Domain for Lab
  redhat.satellite.domain:
    name: "{{ var_subdomain_internal }}"
    description: "Internal Lab Domain"
    locations:
      - "Default Location"
    organizations:
      - "Default Organization"
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    state: present

- name: Create Subnet for Lab
  redhat.satellite.subnet:
    name: "Lab Subnet"
    description: "Subnet for Satellite Lab"
    network: "192.168.0.0"
    mask: "255.255.255.254"
    gateway: "192.168.0.1"
    boot_mode: "DHCP"
    remote_execution_proxies:
      - "satellite.{{ var_subdomain }}"
      - "capsule.{{ var_subdomain }}"
    mtu: 9001
    domains:
      - "{{ var_subdomain_internal }}"
    organizations:
      - "Default Organization"
    locations:
      - "Default Location"
    username: "{{ var_workshop_satellite_user_name }}"
    password: "{{ var_workshop_satellite_user_password }}"
    server_url: "https://{{ var_workshop_satellite_url }}"
    state: present
