---
- include_tasks: fix-name-resolution.yml
- name: Include generate-vars-and-inventory-file.yml
  ansible.builtin.include_tasks:
    file: generate-vars-and-inventory-file.yml
  loop: "{{ rh1_lab19_hosts_satellite_bastion }}"
  loop_control:
    loop_var: _hostname_
- include_tasks: initialize-satellite.yml 
- name: Include register host tasks
  ansible.builtin.include_tasks:
    file: register-host.yml
  loop: "{{ rh1_lab19_satellite_init_hosts }}"
  loop_control:
    loop_var: _hostname_
- include_tasks: get-lab-repo.yml
- name: Register satellite to CDN
  ansible.builtin.include_tasks:
    file: satellite-register.yml
  loop: "{{ rh1_lab19_hosts_satellites }}"
  loop_control:
    loop_var: _hostname_
