---
- include_tasks: fix-name-resolution.yml
#- include_tasks: generate-vars-and-inventory-file.yml
- include_tasks: initialize-satellite.yml 
- name: Include register host tasks
  ansible.builtin.include_tasks:
    file: register-host.yml
  loop: "{{ rh1_lab19_satellite_init_hosts }}"
  loop_control:
    loop_var: _hostname_
