---
- name: create lifecycle environments for the Satellite Server
  redhat.satellite.lifecycle_environment:
    satellite_server_url: "{{ workshop_satellite_url }}"
    satellite_username: "{{ workshop_satellite_user_name }}"
    satellite_password: "{{ workshop_satellite_user_password }}"
    satellite_organization: "Default Organization"
    satellite_lifecycle_environments:
      - name: "Development"
        prior: "Library"
      - name: "Test"
        prior: "Development"
      - name: "Production"
        prior: "Test"

  post_tasks:
  - name: "Enable Directory Server RPMs repositories with label"
    redhat.satellite.repository_set:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      organization: "Default Organization"
      label: dirsrv-12-for-rhel-9-x86_64-rpms
      repositories:
        - releasever: "9"
      state: enabled

  - name: "Enable the Directory Server Repo and set to Immediate"
    redhat.satellite.repository:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      name: "Red Hat Directory Server 12 for RHEL 9 x86_64 RPMs 9"
      state: present
      content_type: "yum"
      product: "Red Hat Directory Server"
      organization: "Default Organization"
      url: "https://cdn.redhat.com/content/dist/rhel9/9/x86_64/resilientstorage/os"
      download_policy: immediate

  - name: "Sync the Directory Server Repo"
    redhat.satellite.repository_sync:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      repository: "Red Hat Directory Server 12 for RHEL 9 x86_64 RPMs 9"
      product: "Red Hat Directory Server"
      organization: "Default Organization"

  - name: "Update the Caspule settings"
    redhat.satellite.smart_proxy:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      name: "capsule.{{ subdomain }}"
      url: "https://capsule.{{ subdomain }}:9090"
      download_policy: "on_demand"
      lifecycle_environments:
        - "Development"
        - "Test"
        - "Production"
      organizations:
        - "Default Organization"
      locations:
        - "Default Location"
      state: present

  - name: "Create or update Red Hat content view"
    redhat.satellite.content_view:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      name: "RHEL 9"
      organization: "Default Organization"
      repositories:
        - name: 'Red Hat Enterprise Linux 9 for x86_64 - AppStream RPMs 9'
          product: 'Red Hat Enterprise Linux for x86_64'
        - name: 'Red Hat Enterprise Linux 9 for x86_64 - BaseOS RPMs 9'
          product: 'Red Hat Enterprise Linux for x86_64'
        - name: 'Red Hat Satellite Client 6 for RHEL 9 x86_64 RPMs'
          product: 'Red Hat Enterprise Linux for x86_64'
    
  - name: "Publish Red Hat Content View"
    redhat.satellite.content_view_version:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      content_view: "RHEL 9"
      organization: "Default Organization"
      version: "1.0"
      lifecycle_environments:
        - Development
        - Test
        - Production

  - name: "Create client activation key"
    redhat.satellite.activation_key:
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      name: "client_key"
      organization: "Default Organization"
      lifecycle_environment: "Development"
      content_view: 'RHEL 9'
      auto_attach: true
      release_version: 9

  - name: Create Domain for Lab
    redhat.satellite.domain:
      name: "{{ subdomain_internal }}"
      description: "Internal Lab Domain"
      locations:
        - "Default Location"
      organizations:
        - "Default Organization"
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      state: present

  - name: Create Subnet for Lab
    redhat.satellite.subnet:
      name: "Lab Subnet"
      description: "Subnet for Satellite Lab"
      network: "192.168.0.0"
      mask: "255.255.255.254"
      gateway: "192.168.0.1"
      boot_mode: "dhcp"
      remote_execution_proxies:
        - "satellite.{{ subdomain }}"
        - "capsule.{{ subdomain }}"
      mtu: 9001
      domains:
        - "{{ subdomain_internal }}"
      organizations:
        - "Default Organization"
      locations:
        - "Default Location"
      username: "{{ workshop_satellite_user_name }}"
      password: "{{ workshop_satellite_user_password }}"
      server_url: "{{ workshop_satellite_url }}"
      state: present
